import { NextPage } from 'next'

import {Layout} from "@components/Layout/Layout";

const HomePage: NextPage = () => {
    return <Layout>gsd</Layout>
}

export default HomePage


// <>
//     <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/public/favicon.ico" />
//     </Head>
//
//     <main className={styles.wrapper}>
//         <button className={styles.btn}>click</button>
//     </main>
// </>